---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# vizoR

<!-- badges: start -->
<!-- badges: end -->

The goal of vizoR is to provide helper functions to help designing better visualizations in R. 

## Installation

This package is under active developpement. You can install it from github: 

``` r
devtools::install_github("aneuraz/vizoR")
```

## Example

### Retrieving a color palette from color-hex.com (by number)

```{r example}
library(vizoR)

pal <- color_hex_palette_from_number(5361)
pal
```

Plotting the palette

```{r plot, fig.asp=0.2}
show_pal(pal)
```

Using the palette

```{r palette usage}
library(ggplot2)

p <- ggplot(mtcars, aes(wt, mpg))
p + geom_point(size = 4, aes(colour = factor(cyl))) +
  scale_color_manual(values = pal) +
  theme_bw()
```

### Using a color-blind proof palette

```{r}

p <- ggplot(mtcars, aes(wt, mpg))
p + geom_point(size = 4, aes(colour = factor(cyl))) +
  scale_color_cbp(black = FALSE) +
  theme_bw()

```


